import nbformat as nbf
import os

# Create notebook object
nb = nbf.v4.new_notebook()

# --- Cell 1: Header ---
md1 = """# Braina Solutions: Master TD

This notebook contains solutions for Problems 3 and 4:
- **Problem 3:** Autoregressive Model Simulation
- **Problem 4:** Single-trial Time-resolved (Dynamic) Functional Connectivity

**Date:** January 15, 2026
**Generated by:** Gemini CLI
"""

# --- Cell 2: Imports ---
code2 = """import numpy as np
import matplotlib.pyplot as plt
import xarray as xr
from frites import set_mpl_style
from frites.simulations import StimSpecAR
from frites.conn import conn_dfc, define_windows

set_mpl_style()""

# --- Cell 3: Problem 3a & 3b Intro ---
md3 = """## 3. Auto-regressive model (3a & 3b)

**Goal:** Simulate a pairwise AR model (Source X -> Target Y) oscillating at 40Hz with 100 trials and a single stimulus.
"""

# --- Cell 4: Problem 3a & 3b Code ---
code4 = """# Parameters
n_epochs = 100
n_stim = 1
ar_type = 'osc_40'

# Initialize AR Simulation
ss_1b = StimSpecAR()

# Fit model (3a: 40Hz, 3b: 100 trials, single stimulus)
ar_data_1b = ss_1b.fit(ar_type=ar_type, n_epochs=n_epochs, n_stim=n_stim)

print("Data shape:", ar_data_1b.shape)

# Plot single trial data and causal coupling (3b)
plt.figure(figsize=(10, 8))
ss_1b.plot(cmap='bwr')
plt.show()"""

# --- Cell 5: Problem 3c Intro ---
md5 = """## 3c. Auto-regressive model (Three Stimuli)

**Goal:** Generate 100 trials with three stimuli and plot the data.
"""

# --- Cell 6: Problem 3c Code ---
code6 = """# Parameters
n_stim_3c = 3

# Initialize AR Simulation
ss_3c = StimSpecAR()

# Fit model with 3 stimuli
ar_data_3c = ss_3c.fit(ar_type=ar_type, n_epochs=n_epochs, n_stim=n_stim_3c)

# Plot
plt.figure(figsize=(10, 8))
ss_3c.plot(cmap='bwr')
plt.show()"""

# --- Cell 7: Problem 3d Equation ---
md7 = """## 3d. AR Model Equation

Based on the source code inspection of `frites.simulations.StimSpecAR` (specifically the `osc_40` type), the data is generated using the following equations for a pairwise system $X \to Y$:

**Source X (Autoregressive only):**
$$ X(t) = 0.55 X(t-1) - 0.8 X(t-2) + \eta_X(t) $$

**Target Y (Autoregressive + Coupling from X):**
$$ Y(t) = 0.35 Y(t-1) - 0.5 Y(t-2) + C(t) \cdot (0.5 X(t-1)) + \eta_Y(t) $$

Where:
- $\eta(t)$ is Gaussian noise.
- $C(t)$ is the time-varying coupling strength modulated by the stimulus (Gaussian profile).
"""

# --- Cell 8: Problem 4 Intro ---
md8 = """## 4. Single-trial time-resolved (dynamic) Functional Connectivity

**Goal:** Estimate DFC between X and Y using the data from 3b.
**Parameters:** Window length = 0.75s, Step = 0.02s.
"""

# --- Cell 9: Problem 4a Code ---
code9 = """# 4a. Compute DFC and plot average time course

# Parameters
win_len = 0.75
win_step = 0.02

# Extract times and ROI from the dataset
times = ar_data_1b.times.values
roi = ar_data_1b.roi.values

# Define sliding windows
# define_windows returns (win_sample, win_time, win_len) - we need win_sample
win_sample = define_windows(times, slwin_len=win_len, slwin_step=win_step)[0]

print(f"Number of windows: {len(win_sample)}")

# Compute DFC (Mutual Information by default)
# Input: (n_epochs, n_roi, n_times)
# Output: (n_epochs, n_pairs, n_windows)
dfc_1b = conn_dfc(ar_data_1b, win_sample, times=times, roi=roi, n_jobs=1, verbose=False)

# Average across trials
dfc_mean = dfc_1b.mean('trials')

# Plot
plt.figure(figsize=(10, 6))
dfc_mean.plot.line(x='times', hue='roi', linewidth=2)
plt.title(f'Mean Dynamic Functional Connectivity (Window: {win_len}s)')
plt.ylabel('Mutual Information (bits)')
plt.grid(True)
plt.show()"""

# --- Cell 10: Problem 4b Intro ---
md10 = """## 4b. Test different window lengths

**Goal:** Evaluate the effect of window length on the DFC estimate.
"""

# --- Cell 11: Problem 4b Code ---
code11 = """# 4b. Test different window lengths
window_lengths = [0.2, 0.5, 0.75, 1.0]

plt.figure(figsize=(15, 10))

for i, w_len in enumerate(window_lengths):
    try:
        # Define windows
        win_sample_i = define_windows(times, slwin_len=w_len, slwin_step=win_step)[0]
        
        # Compute DFC
        dfc_i = conn_dfc(ar_data_1b, win_sample_i, times=times, roi=roi, n_jobs=1, verbose=False)
        
        # Average
        dfc_mean_i = dfc_i.mean('trials')
        
        # Plot
        ax = plt.subplot(2, 2, i+1)
        # Plot all pairs (usually just one x-y in this simulation)
        for r in dfc_mean_i.roi.values:
            dfc_mean_i.sel(roi=r).plot(ax=ax, label=r)
            
        plt.title(f'Window Length: {w_len}s')
        plt.grid(True)
        plt.legend()
    except Exception as e:
        print(f"Could not compute for window {w_len}s: {e}")

plt.suptitle('Effect of Window Length on DFC')
plt.tight_layout()
plt.show()

# Interpretation:
# Smaller windows (0.2s) provide higher temporal resolution but noisier estimates.
# Larger windows (1.0s) provide smoother estimates but smear the temporal dynamics (lower temporal resolution),
# potentially missing the onset/offset of the coupling.
# The 0.75s window appears to be a compromise, capturing the rise in connectivity aligned with the stimulus.
"""

# Append cells to notebook
b['cells'] = [
    nbf.v4.new_markdown_cell(md1),
    nbf.v4.new_code_cell(code2),
    nbf.v4.new_markdown_cell(md3),
    nbf.v4.new_code_cell(code4),
    nbf.v4.new_markdown_cell(md5),
    nbf.v4.new_code_cell(code6),
    nbf.v4.new_markdown_cell(md7),
    nbf.v4.new_markdown_cell(md8),
    nbf.v4.new_code_cell(code9),
    nbf.v4.new_markdown_cell(md10),
    nbf.v4.new_code_cell(code11)
]

# Write file
output_path = 'usecases/master_td/braina_solutions_TD.ipynb'
with open(output_path, 'w') as f:
    nbf.write(nb, f)

print(f"Notebook created at: {output_path}")
